name: Pytest (all)

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: "pip"  # NEW caches pip dependencies!
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
      # Plugins: pep8-naming, flake8-pytest, flake8-simplify
        pip install flake8 pep8-naming flake8-pytest flake8-simplify
    - name: "Lint — flake8"
      # Run all tests (in 'tests/*' folder)
      run: |
      # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
      # exit-zero treats all errors as warnings. Our project currently prefers 120 as max
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=120 --statistics
